#!/bin/bash

#-----------------------------------
#  colors
#-----------------------------------
red='\e[0;31m'
RED='\e[1;31m'
blue='\e[0;34m'
BLUE='\e[1;34m'
cyan='\e[0;36m'
CYAN='\e[1;36m'
NC='\e[0m'      # no color
black='\e[0;30m'
BLACK='\e[1;30m'
green='\e[0;32m'
GREEN='\e[1;32m'
yellow='\e[0;33m'
YELLOW='\e[1;33m'
magenta='\e[0;35m'
MAGENTA='\e[1;35m'
#white='\e[0;37m'
white='\e[0;37m'
WHITE='\e[1;37m'
#-----------------------------------
#  symbols
#-----------------------------------
SYM_1='\xe2\x94\x8c' # ┌
SYM_2='\xe2\x94\x80' # ─
SYM_3='\xe2\x94\x94' # └
SYM_4='\xe2\x8a\xa2' # ⊢
SYM_5='\xe2\x8a\xa3' # ⊣
SYM_7='\xe2\x95\xbc' # ╼
SYM_8='\xe2\x8a\x8f' # ⊏
SYM_9='\xe2\x8a\x90' # ⊐
SYM_10='\xe2\x8a\x82' # ⊂
SYM_11='\xe2\x8a\x83' # ⊃
SYM_12='\xe2\x94\x9c' # ├
SYM_13='\xe2\x94\xa4' # ┤
SYM_14='\xe2\x94\x82' # │



