#!/bin/bash

function symbol() {
   echo -e $(symbol_string $@) 
}

function symbol_string() {
   local prefix=\\x
   local symbol=$prefix$1
   symbol+=$prefix$2
   symbol+=$prefix$3
   echo $symbol
}

function symbol_config() {
   local sym="SYM_$4"
   sym+="='$(symbol_string $1 $2 $3)'"
   sym+=" # $(symbol $1 $2 $3)"
   echo $sym
}

function symbols_iterate_e2() {
   echo '#----------------------------------'
   echo '# e2 '$1
   echo '#----------------------------------'
   
   END=191
   for ((i=128;i<=END;i++)); do
      local hex="$(printf "%x" $i)"
      local str="$(symbol_string e2 $1 $hex)"
      echo -n "SYM_$1_$i='$str' # "
      echo -e "$str\n"
   done
}


function _symbols_iterate_e2_94() {
   END=191
   for ((i=128;i<=END;i++)); do
      local hex="$(printf "%x" $i)"
      local str="$(symbol_string e2 94 $hex)"
      echo -n "SYM_$i='$str' # "
      echo -e "$str\n"
   done
}

function symbols_iterate_e2_95() {
   END=191
   for ((i=128;i<=END;i++)); do
      local hex="$(printf "%x" $i)"
      local str="$(symbol_string e2 95 $hex)"
      echo -n "SYM_$i='$str' # "
      echo -e "$str\n"
   done
}

function symbols_iterate() {
   symbols_iterate_e2 90 >> symbols_e2.txt
   symbols_iterate_e2 91 >> symbols_e2.txt
   symbols_iterate_e2 92 >> symbols_e2.txt
   symbols_iterate_e2 93 >> symbols_e2.txt
   symbols_iterate_e2 94 >> symbols_e2.txt
   symbols_iterate_e2 95 >> symbols_e2.txt
   symbols_iterate_e2 96 >> symbols_e2.txt
   symbols_iterate_e2 97 >> symbols_e2.txt
   symbols_iterate_e2 98 >> symbols_e2.txt
   symbols_iterate_e2 99 >> symbols_e2.txt

}
